In [14]:
import numpy as np

In [12]:
import pandas as pd

In [15]:
df = pd.read_csv("data.csv")

In [16]:
print(df)

                 Actor                      Film  Year            Genre  \
0       Shah Rukh Khan                   Pathaan  2023           Action
1          Salman Khan           Tiger Zinda Hai  2017           Action
2           Aamir Khan                    Dangal  2016        Biography
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
4        Ranveer Singh                 Padmaavat  2018       Historical
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
6        Rajkummar Rao                     Stree  2018    Horror Comedy
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
1                    565   6.0
2                   2024   8.4
3                    431   5.6
4                    585   7.0
5                    111   8.3
6                    180   7.5
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2

In [19]:
df = pd.read_json("data.json")
print(df)

       name  age       city
0  Siddhant   21       pune
1   Anushka   23     mumbai
2    Gaurav   25      delhi
3     Onkar   28  Bangalore

In [21]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [22]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [23]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [24]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [26]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [29]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [30]:
df.shape

(244, 7)