# Pandas Data Cleaning and Handling Missing Values

In real-world data analysis, datasets are rarely clean. They often contain missing values, placeholder values, or incorrect data types. Pandas provides a powerful and flexible set of tools to identify, clean, and resolve these issues.

This tutorial covers:
1. **Detecting Missing Values** (`isna()`, `isnull()`, `.sum()`)
2. **Dropping Missing Data** (`dropna()`)
3. **Filling Missing Data** (`fillna()`, forward fill, backward fill)
4. **Replacing Values** (`replace()`)

In [1]:
import pandas as pd
import numpy as np

## 1. Detecting Missing Values

Let's create a sample DataFrame representing student records, with some missing values (`None` or `np.nan`).

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [20.0, np.nan, 22.0, 21.0, 19.0],
    'Score': [85.0, 90.0, np.nan, 88.0, np.nan],
    'City': ['New York', None, 'Boston', 'Chicago', None]
}
df = pd.DataFrame(data)
df

      Name   Age  Score      City
0    Alice  20.0   85.0  New York
1      Bob   NaN   90.0      None
2  Charlie  22.0    NaN    Boston
3    David  21.0   88.0   Chicago
4      Eva  19.0    NaN      None

To detect missing values, we use `.isna()` (or its alias `.isnull()`). This returns a boolean DataFrame of the same shape.

In [3]:
df.isna()

    Name    Age  Score   City
0  False  False  False  False
1  False   True  False   True
2  False  False   True  False
3  False  False  False  False
4  False  False   True   True

To count the number of missing values in each column, chain it with `.sum()`.

In [4]:
df.isna().sum()

Name     0
Age      1
Score    2
City     2
dtype: int64

## 2. Dropping Missing Data

We can use `.dropna()` to remove rows or columns containing missing values.

By default, `dropna()` drops any row that has at least one missing value (`how='any'`).

In [5]:
# Drop rows with any NaN values
df.dropna()

    Name   Age  Score      City
0  Alice  20.0   85.0  New York
3  David  21.0   88.0   Chicago

To drop columns instead of rows, use `axis=1` or `axis='columns'`.

In [6]:
# Drop columns with any NaN values - since 'Name' is the only fully populated column, we select only it.
# Note: df is not modified unless inplace=True is set.
df.dropna(axis=1)

      Name   Age  Score      City
0    Alice  20.0   85.0  New York
1      Bob   NaN   90.0      None
2  Charlie  22.0    NaN    Boston
3    David  21.0   88.0   Chicago
4      Eva  19.0    NaN      None

## 3. Filling Missing Data

Instead of discarding data, we can fill missing values using `.fillna()`.

In [7]:
# Fill numerical NaNs with 0 and strings with 'Unknown'
df.fillna({'Age': 0, 'Score': 0, 'City': 'Unknown'})

      Name   Age  Score      City
0    Alice  20.0   85.0  New York
1      Bob   0.0   90.0   Unknown
2  Charlie  22.0    0.0    Boston
3    David  21.0   88.0   Chicago
4      Eva  19.0    0.0   Unknown

We can also fill missing values dynamically with summary statistics like the **mean** or **median** of the column.

In [8]:
# Fill Age and Score with their respective mean values
df_clean = df.copy()
df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].mean())
df_clean['Score'] = df_clean['Score'].fillna(df_clean['Score'].mean())
df_clean

      Name   Age      Score      City
0    Alice  20.0  85.000000  New York
1      Bob  20.5  90.000000      None
2  Charlie  22.0  87.666667    Boston
3    David  21.0  88.000000   Chicago
4      Eva  19.0  87.666667      None

### Forward Fill and Backward Fill

For sequential or time-series data, we can propagate non-null values forward (`ffill`) or backward (`bfill`).

In [9]:
# Forward fill propagates the last valid observation down to next valid
df.ffill()

      Name   Age  Score      City
0    Alice  20.0   85.0  New York
1      Bob  20.0   90.0  New York
2  Charlie  22.0   90.0    Boston
3    David  21.0   88.0   Chicago
4      Eva  19.0   88.0   Chicago

## 4. Replacing Values

Sometimes, missing values or placeholders are written as specific characters (like `"?"`, `"N/A"`, or `-999`). We can use `.replace()` to swap them out.

In [10]:
df_raw = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [1200, -999, 80, '?']
})

# Replace -999 and '?' with NaN to mark them as missing values
df_clean_prices = df_raw.replace([-999, '?'], np.nan)
df_clean_prices

    Product   Price
0    Laptop  1200.0
1     Mouse     NaN
2  Keyboard    80.0
3   Monitor     NaN

In [4]:
df = pd.read_csv("data_cleaning_sample.csv")

In [5]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [7]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [8]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [9]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [10]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [11]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [13]:
df.fillna({'Age': 0, 'Name': 'Unknown', 'Join Date': '1-1-2000'})

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5  Unknown  28.0        Delhi      F     eve@domain.com    1-1-2000
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [14]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [16]:
df.fillna(method="ffill")

/var/folders/fh/4blh4pwd47d40m76xn2cn4n00000gn/T/ipykernel_5742/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [20]:
df.fillna(method="bfill")

/var/folders/fh/4blh4pwd47d40m76xn2cn4n00000gn/T/ipykernel_5742/3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [21]:
df.fillna(method="bfill")

/var/folders/fh/4blh4pwd47d40m76xn2cn4n00000gn/T/ipykernel_5742/3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [22]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021