In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("data.csv")
print(df)

                 Actor                      Film  Year            Genre  \
0       Shah Rukh Khan                   Pathaan  2023           Action
1          Salman Khan           Tiger Zinda Hai  2017           Action
2           Aamir Khan                    Dangal  2016        Biography
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
4        Ranveer Singh                 Padmaavat  2018       Historical
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
6        Rajkummar Rao                     Stree  2018    Horror Comedy
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
1                    565   6.0
2                   2024   8.4
3                    431   5.6
4                    585   7.0
5                    111   8.3
6                    180   7.5
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2

In [6]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [10]:
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [11]:
df.loc[3]

Actor                   Ranbir Kapoor
Film                       Brahmastra
Year                             2022
Genre                         Fantasy
BoxOffice(INR Crore)              431
IMDb                              5.6
Name: 3, dtype: object

In [12]:
# Filter movies with IMDb rating > 8.0
df[df["IMDb"] > 8.0]

                 Actor                      Film  Year      Genre  BoxOffice(INR Crore)  IMDb
2           Aamir Khan                    Dangal  2016  Biography                  2024   8.4
5   Ayushmann Khurrana                 Andhadhun  2018   Thriller                   111   8.3
11       Vicky Kaushal  Uri: The Surgical Strike  2019     Action                   342   8.2

In [13]:
# Filter Action movies with Box Office > 500 Crore
df[(df["Genre"] == "Action") & (df["BoxOffice(INR Crore)"] > 500)]

            Actor             Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan          Pathaan  2023  Action                  1050   7.2
1     Salman Khan  Tiger Zinda Hai  2017  Action                   565   6.0