# Pandas Grouping and Aggregations

Grouping data and calculating aggregations is one of the most common tasks in data analysis (similar to SQL's `GROUP BY`). Pandas provides the split-apply-combine workflow using the `.groupby()` method.

This tutorial covers:
1. **Basic Grouping** (`groupby()`)
2. **Built-in Aggregation Functions** (`sum()`, `mean()`, `count()`)
3. **Grouping by Multiple Columns**
4. **Custom Aggregations** with `.agg()`

In [1]:
import pandas as pd
import numpy as np

## 1. Creating a Sample Sales Dataset

Let's create a DataFrame representing sales transactions across multiple categories and regions.

In [2]:
data = {
    'Category': ['Electronics', 'Furniture', 'Electronics', 'Office Supplies', 'Furniture', 'Electronics', 'Office Supplies'],
    'Region': ['East', 'West', 'West', 'East', 'East', 'East', 'West'],
    'Sales': [250.0, 350.0, 120.0, 15.0, 450.0, 300.0, 45.0],
    'Quantity': [2, 1, 4, 10, 3, 1, 5]
}
df = pd.DataFrame(data)
df

          Category Region  Sales  Quantity
0      Electronics   East  250.0         2
1        Furniture   West  350.0         1
2      Electronics   West  120.0         4
3  Office Supplies   East   15.0        10
4        Furniture   East  450.0         3
5      Electronics   East  300.0         1
6  Office Supplies   West   45.0         5

## 2. Basic Grouping and Aggregating

To compute aggregate metrics per Category, we call `groupby('Category')` followed by a summary function. For instance, let's find the **total Sales** per Category.

In [3]:
# Group by Category and sum only the 'Sales' column
df.groupby('Category')[['Sales']].sum()

                 Sales
Category
Electronics      670.0
Furniture        800.0
Office Supplies   60.0

We can calculate the average (mean) Sales and Quantity per Category:

In [4]:
# Compute mean for all numerical columns in the group
df.groupby('Category')[['Sales', 'Quantity']].mean()

                      Sales  Quantity
Category
Electronics      223.333333  2.333333
Furniture        400.000000  2.000000
Office Supplies   30.000000  7.500000

## 3. Grouping by Multiple Columns

We can group by multiple columns by passing a list to `.groupby()`. This creates a **MultiIndex** DataFrame.

In [5]:
# Group by both Category and Region
multi_group = df.groupby(['Category', 'Region']).sum()
multi_group

                            Sales  Quantity
Category        Region
Electronics     East        550.0         3
                West        120.0         4
Furniture       East        450.0         3
                West        350.0         1
Office Supplies East         15.0        10
                West         45.0         5

To convert a MultiIndex back to standard columns, call `.reset_index()`.

In [6]:
multi_group.reset_index()

          Category Region  Sales  Quantity
0      Electronics   East  550.0         3
1      Electronics   West  120.0         4
2        Furniture   East  450.0         3
3        Furniture   West  350.0         1
4  Office Supplies   East   15.0        10
5  Office Supplies   West   45.0         5

## 4. Custom Aggregations using `.agg()`

The `.agg()` method offers ultimate flexibility, allowing you to:
- Apply multiple statistical functions to a single column.
- Apply different functions to different columns.

In [7]:
# Perform multiple aggregations on Sales, and find max on Quantity
df.groupby('Category').agg({
    'Sales': ['sum', 'mean'],
    'Quantity': 'max'
})

                 Sales                  Quantity
                   sum        mean           max
Category
Electronics      670.0  223.333333             4
Furniture        800.0  400.000000             3
Office Supplies   60.0   30.000000            10