# Pandas Merging, Joining, and Concatenating

In real-world applications, data is often spread across multiple tables or files. Pandas provides high-performance relational join operations that are incredibly similar to SQL joins.

This tutorial covers:
1. **Concatenation** (`pd.concat()`) - Stacking DataFrames vertically or horizontally
2. **Merging** (`pd.merge()`) - Relational database-style joins on keys (Inner, Left, Right, Outer)
3. **Joining** (`.join()`) - Index-based merges

In [1]:
import pandas as pd

## 1. Concatenating DataFrames (`pd.concat()`)

`pd.concat()` is used to combine DataFrames along a particular axis (rows or columns).

In [2]:
df1 = pd.DataFrame({'Employee': ['Alice', 'Bob'], 'Department': ['HR', 'Engineering']})
df2 = pd.DataFrame({'Employee': ['Charlie', 'David'], 'Department': ['Marketing', 'Finance']})

# Stack DataFrames vertically (axis=0 is default)
pd.concat([df1, df2])

  Employee   Department
0    Alice           HR
1      Bob  Engineering
0  Charlie    Marketing
1    David      Finance

To reset the index when stacking, use `ignore_index=True`.

In [3]:
pd.concat([df1, df2], ignore_index=True)

  Employee   Department
0    Alice           HR
1      Bob  Engineering
2  Charlie    Marketing
3    David      Finance

## 2. Merging DataFrames (`pd.merge()`)

`pd.merge()` joins DataFrames based on common key columns, allowing all SQL-style joins:
- **Inner Join**: Keep only keys present in both DataFrames (default).
- **Left Join**: Keep all keys from the left DataFrame.
- **Right Join**: Keep all keys from the right DataFrame.
- **Outer Join**: Keep all keys from both DataFrames.

In [4]:
df_emp = pd.DataFrame({
    'Emp_ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

df_sal = pd.DataFrame({
    'Emp_ID': [2, 3, 4, 5],
    'Salary': [70000, 80000, 120000, 95000]
})

### Inner Join
Returns records with matching Emp_IDs in both tables.

In [5]:
pd.merge(df_emp, df_sal, on='Emp_ID', how='inner')

   Emp_ID     Name  Salary
0       2      Bob   70000
1       3  Charlie   80000
2       4    David  120000

### Left Join
Returns all employees, filling Salary with `NaN` if they aren't present in the salary DataFrame.

In [6]:
pd.merge(df_emp, df_sal, on='Emp_ID', how='left')

   Emp_ID     Name    Salary
0       1    Alice       NaN
1       2      Bob   70000.0
2       3  Charlie   80000.0
3       4    David  120000.0

### Outer Join
Returns all records from both DataFrames, inserting `NaN` wherever a match is missing.

In [7]:
pd.merge(df_emp, df_sal, on='Emp_ID', how='outer')

   Emp_ID     Name    Salary
0       1    Alice       NaN
1       2      Bob   70000.0
2       3  Charlie   80000.0
3       4    David  120000.0
4       5      NaN   95000.0

## 3. Joining DataFrames (`.join()`)

`.join()` is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single DataFrame based on the **index**.

In [8]:
left = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie']}, index=['a', 'b', 'c'])
right = pd.DataFrame({'Age': [25, 30]}, index=['a', 'b'])

# Join left and right using indices
left.join(right)

      Name   Age
a    Alice  25.0
b      Bob  30.0
c  Charlie   NaN